# trigger workflow
name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t starttech-backend:latest ./backend

      - name: Tag Docker image
        run: docker push 597088021675.dkr.ecr.us-east-1.amazonaws.com/starttech-backend:latest
      - name: Push to ECR
        run: docker push 597088021675.dkr.ecr.us-east-1.amazonaws.com/starttech-backend:latest
      - name: Deploy Terraform infrastructure
        run: |
          cd starttech-infra/terraform
          terraform init -reconfigure
          terraform apply -auto-approve

